# core application settings
spring.application.name=travelx
logging.pattern.console=[%d{ISO8601} %d{z}] %.-1level travelx [%t] %X{TransactionId} %c{1}.%M %m%n
spring.main.banner-mode=OFF

# server settings
server.servlet.context-path=/travelx
server.port=8080

# infrastructure settings
travelx.request-logging.enabled=true
travelx.request-logging.exclude-paths=/api/*chat

logging.level.sk.mkrajcovic.travelx=DEBUG
